- name: Add tendrl master repo
  yum_repository:
    name: tendrl
    description: Copr repo for tendrl owned by tendrl
    baseurl: "http://copr-be.cloud.fedoraproject.org/results/tendrl/release/epel-7-x86_64/"
  when: enable_master_repo

- name: Copy rpm-gpg key first (hack)
  copy:
    src='rpm-tendrl-pubkey.gpg'
    dest=/root
  when: enable_master_repo

- name: Add public key for master repo
  rpm_key:
    key="/root/rpm-tendrl-pubkey.gpg"
  when: enable_master_repo

- name: Add tendrl develop repo
  yum_repository:
    name: tendrl-develop
    description: Copr repo for tendrl owned by tendrl
    baseurl: "http://copr-be.cloud.fedoraproject.org/results/tendrl/tendrl-develop/epel-7-x86_64/"
  when: enable_develop_repo

- name: Copy rpm-gpg key first (hack)
  copy:
    src='rpm-tendrl-develop-pubkey.gpg'
    dest=/root
  when: enable_develop_repo

- name: Add public key for develop repo
  rpm_key:
    key="/root/rpm-tendrl-develop-pubkey.gpg"
  when: enable_develop_repo

- name: Add tendrl dependencies repo
  yum_repository:
    name: tendrl-dependencies
    description: Copr repo for tendrl dependencies owned by tendrl
    baseurl: "http://copr-be.cloud.fedoraproject.org/results/tendrl/dependencies/epel-7-x86_64/"

- name: Copy rpm-gpg key first (hack)
  copy:
    src='rpm-tendrl-dependencies-pubkey.gpg'
    dest=/root

- name: Add public key for dependencies repo
  rpm_key:
    key="/root/rpm-tendrl-dependencies-pubkey.gpg"
