---

#
# usmqe test user (the tests are executed under this account)
#

- name: Create usmqe unix user group
  group: name=usmqe state=present

- name: Create usmqe unix user account
  user:
    name=usmqe
    group=usmqe
    createhome=yes
    generate_ssh_key=yes
    comment="USM QE test user account"
    state=present

#
# ansible
#

- name: Install ansible
  yum: name=ansible state=present enablerepo=epel

- name: Configure ansible forks option
  ini_file:
    dest=/etc/ansible/ansible.cfg
    section=defaults
    option=forks
    value=50

- name: Configure ansible host_key_checking option
  ini_file:
    dest=/etc/ansible/ansible.cfg
    section=defaults
    option=host_key_checking
    value=False

# Required to overcome ssh control path socket errors for very long hostnames.
- name: Configure ansible control_path
  ini_file:
    dest=/etc/ansible/ansible.cfg
    section=ssh_connection
    option=control_path
    value='%(directory)s/%%h-%%r'

#
# usmqe dependencies
#

- name: Install usmqe dependencies from rh-python-35 collection
  yum: name={{ item }} state=installed
  with_items:
   - rh-python35-PyYAML
   - rh-python35-python-jinja2

#
# other tools
#

- name: Install other useful tools
  yum: name={{ item }} state=installed enablerepo=epel
  with_items:
   - git
   - vim
   - tmux
   - htop
   - tree
