---
gluster_nodes: "{{groups['gluster']}}"
volumename: "TestVolumeA"
num_bricks: 1
## FIXME: this doesn't work because of bug in ansible-gluster - glusterbrick module
# set replica to 0 to create just distributed volume (disable replica)
#- replica: 2
